[workspace]
resolver = "2"
members = ["src/cli"]

[workspace.package]
version = "0.1.0"
description = "Pidgeon CLI"
authors = ["Hrvoje Jurić <hrvoje@altibiz.com>"]
license = "MIT"
readme = "README.md"
edition = "2021"

[workspace.metadata]
crane.name = "pidgeon"
