[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixpkgs-fmt" }
language-server = { command = "nil" }

[[language]]
name = "rust"
auto-format = true
language-server = { command = "rust-analyzer" }

[language-server.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false

[[language]]
name = "python"
auto-format = true
formatter = { command = "yapf" }
language-server = { command = "pyright-langserver", args = ["--stdio"] }

[[language]]
name = "bash"
auto-format = true
formatter = { command = "shfmt" }
language-server = { command = "bash-language-server", args = ["start"] }

[[language]]
name = "toml"
auto-format = true
language-server = { command = "taplo", args = ["lsp", "stdio"] }

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "prettier", args = [
  "--parser",
  "yaml",
  "--prose-wrap",
  "always",
] }
language-server = { command = "yaml-language-server", args = ["--stdio"] }

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "prettier", args = [
  "--parser",
  "markdown",
  "--prose-wrap",
  "always",
] }
language-server = { command = "marksman", args = ["server"] }
