[language-server]
nil = { command = "nil" }
bash-language-server = { command = "bash-language-server", args = ["start"] }
taplo = { command = "taplo", args = ["lsp", "stdio"] }
yaml-language-server = { command = "yaml-language-server", args = ["--stdio"] }
marksman =  { command = "marksman", args = ["server"] }

[language-server.pyright-langserver]
command = "poetry"
args = ["run", "pyright-langserver", "--stdio"]
timeout = 10000

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false

[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixpkgs-fmt" }
language-servers = [ "nil" ]

[[language]]
name = "rust"
auto-format = true
language-servers = [ "rust-analyzer" ]

[[language]]
name = "python"
auto-format = true
formatter = { command = "poetry", args = ["run", "yapf"] }
language-servers = [ "pyright-langserver" ]

[[language]]
name = "bash"
auto-format = true
formatter = { command = "shfmt" }
language-servers = [ "bash-language-server" ]

[[language]]
name = "toml"
auto-format = true
language-servers = [ "taplo" ]

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "prettier", args = [
  "--parser",
  "yaml",
  "--prose-wrap",
  "always",
] }
language-servers = [ "yaml-language-server" ]

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "prettier", args = [
  "--parser",
  "markdown",
  "--prose-wrap",
  "always",
] }
language-servers = [ "marksman" ]
