[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixpkgs-fmt" }
language-server = { command = "nil" }

[[language]]
name = "rust"
auto-format = true
formatter = { command = "rustfmt" }
language-server = { command = "rust-analyzer" }

[language-server.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false

[[language]]
name = "python"
auto-format = true
formatter = { command = "yapf" }
language-server = { command = "pyright-langserver", args = ["--stdio"] }

[[language]]
name = "toml"
auto-format = true
formatter = { command = "taplo", args = ["fmt"] }
language-server = { command = "taplo", args = ["lsp", "stdio"] }
