[language-server]
nil = { command = "nil" }
pyright-langserver = { command = "pyright-langserver", args = ["--stdio"] }
bash-language-server = { command = "bash-language-server", args = ["start"] }
taplo = { command = "taplo", args = ["lsp", "stdio"] }
yaml-language-server = { command = "yaml-language-server", args = ["--stdio"] }
marksman = { command = "marksman", args = ["server"] }

[language-server.rust-analyzer]
command = "rust-analyzer"

[language-server.rust-analyzer.config]
inlayHints.bindingModeHints.enable = false
inlayHints.closingBraceHints.minLines = 10
inlayHints.closureReturnTypeHints.enable = "with_block"
inlayHints.discriminantHints.enable = "fieldless"
inlayHints.lifetimeElisionHints.enable = "skip_trivial"
inlayHints.typeHints.hideClosureInitialization = false

[[language]]
name = "nix"
auto-format = true
formatter = { command = "nixpkgs-fmt" }
language-servers = ["nil"]

[[language]]
name = "rust"
auto-format = true
language-servers = ["rust-analyzer"]

[language.debugger]
name = "lldb-vscode"
transport = "stdio"
command = "lldb-vscode"

[[language.debugger.templates]]
name = "cli"
request = "launch"
completion = []

[language.debugger.templates.args]
program = "target/debug/pidgeon-cli"
args = ["--config", "src/cli/config.toml"]

[[language]]
name = "python"
auto-format = true
formatter = { command = "yapf" }
language-servers = ["pyright-langserver"]

[[language]]
name = "bash"
auto-format = true
formatter = { command = "shfmt" }
language-servers = ["bash-language-server"]

[[language]]
name = "toml"
auto-format = true
language-servers = ["taplo"]

[[language]]
name = "yaml"
auto-format = true
formatter = { command = "prettier", args = [
  "--parser",
  "yaml",
  "--prose-wrap",
  "always",
] }
language-servers = ["yaml-language-server"]

[[language]]
name = "markdown"
auto-format = true
formatter = { command = "prettier", args = [
  "--parser",
  "markdown",
  "--prose-wrap",
  "always",
] }
language-servers = ["marksman"]
