[package]
name = "pidgeon-cli"
version = "0.1.0"
description = "Pidgeon CLI"
authors = ["Hrvoje Jurić <hrvoje@altibiz.com>"]
license = "MIT"
readme = "README.md"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
async-trait = "0.1.74"
chrono = { version = "0.4.26", features = ["serde"] }
clap = { version = "4.4.0", features = ["derive"] }
directories = "5.0.1"
dotenv = "0.15.0"
either = { version = "1.9.0", features = ["serde"] }
env_logger = "0.10.0"
flume = "0.11.0"
futures = "0.3.29"
futures-core = "0.3.29"
futures-time = "3.0.0"
ipnet = { version = "2.8.0", features = ["serde"] }
itertools = "0.11.0"
log = { version = "0.4.20", features = ["serde"] }
regex = "1.9.4"
reqwest = { version = "0.11.20", features = [
  "json",
  "rustls",
  "rustls-tls",
  "gzip",
] }
rustls = "0.21.6"
serde = { version = "1.0.186", features = ["derive"] }
serde_json = "1.0.105"
serde_yaml = "0.9.25"
sqlx = { version = "0.7.1", features = [
  "postgres",
  "runtime-tokio",
  "tls-rustls",
  "chrono",
  "ipnetwork",
  "json",
] }
thiserror = "1.0.47"
tokio = { version = "1.32.0", features = ["full"] }
tokio-modbus = { version = "0.9.0", features = ["tcp", "rtu"] }
tokio-util = { version = "0.7.8", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
uuid = { version = "1.5.0", features = ["v4", "fast-rng"] }
