# schneider-iEM3xxx

[[modbus.devices.schneider-iEM3xxx.detect]]
address = 0x0031
match = "iEM3255"
kind = { string = { length = 20 } }

[[modbus.devices.schneider-iEM3xxx.id]]
address = 0x0081
kind = { u32 = { multiplier = 1 } }

# schneider-iEM3xxx instantaneous

[[modbus.devices.schneider-iEM3xxx.measurement]]
name = "voltageL1_V"
address = 0x0BD3
kind = { f32 = { multiplier = 1 } }

[[modbus.devices.schneider-iEM3xxx.measurement]]
name = "voltageL2_V"
address = 0x0BD5
kind = { f32 = { multiplier = 1 } }

[[modbus.devices.schneider-iEM3xxx.measurement]]
name = "voltageL3_V"
address = 0x0BD7
kind = { f32 = { multiplier = 1 } }

[[modbus.devices.schneider-iEM3xxx.measurement]]
name = "currentL1_A"
address = 0x0BB7
kind = { f32 = { multiplier = 1 } }

[[modbus.devices.schneider-iEM3xxx.measurement]]
name = "currentL2_A"
address = 0x0BB9
kind = { f32 = { multiplier = 1 } }

[[modbus.devices.schneider-iEM3xxx.measurement]]
name = "currentL3_A"
address = 0x0BBB
kind = { f32 = { multiplier = 1 } }

[[modbus.devices.schneider-iEM3xxx.measurement]]
name = "activePowerL1_W"
address = 0x0BED
kind = { f32 = { multiplier = 1000 } }

[[modbus.devices.schneider-iEM3xxx.measurement]]
name = "activePowerL2_W"
address = 0x0BEF
kind = { f32 = { multiplier = 1000 } }

[[modbus.devices.schneider-iEM3xxx.measurement]]
name = "activePowerL3_W"
address = 0x0BF1
kind = { f32 = { multiplier = 1000 } }

[[modbus.devices.schneider-iEM3xxx.measurement]]
name = "reactivePowerTotal_VAR"
address = 0x0BFB
kind = { f32 = { multiplier = 1000 } }

[[modbus.devices.schneider-iEM3xxx.measurement]]
name = "apparentPowerTotal_VA"
address = 0x0C03
kind = { f32 = { multiplier = 1000 } }

# schneider-iEM3xxx cumulative

[[modbus.devices.schneider-iEM3xxx.measurement]]
name = "activeEnergyImportTotal_Wh"
address = 0x0C83
kind = { s64 = { multiplier = 1 } }

[[modbus.devices.schneider-iEM3xxx.measurement]]
name = "activeEnergyExportTotal_Wh"
address = 0x0C87
kind = { s64 = { multiplier = 1 } }

[[modbus.devices.schneider-iEM3xxx.measurement]]
name = "reactiveEnergyImportTotal_VARh"
address = 0x0C93
kind = { s64 = { multiplier = 1 } }

[[modbus.devices.schneider-iEM3xxx.measurement]]
name = "reactiveEnergyExportTotal_VARh"
address = 0x0C97
kind = { s64 = { multiplier = 1 } }

# abb-B2x

[[modbus.devices.abb-B2x.detect]]
address = 0x8960
match = "B23 [0-9]12-100"
kind = { string = { length = 6 } }

[[modbus.devices.abb-B2x.id]]
address = 0x8900
kind = { u32 = { multiplier = 1 } }

# abb-B2x instantaneous

[[modbus.devices.abb-B2x.measurement]]
name = "voltageL1_V"
address = 0x5B00
kind = { u32 = { multiplier = 0.1 } }

[[modbus.devices.abb-B2x.measurement]]
name = "voltageL2_V"
address = 0x5B02
kind = { u32 = { multiplier = 0.1 } }

[[modbus.devices.abb-B2x.measurement]]
name = "voltageL3_V"
address = 0x5B04
kind = { u32 = { multiplier = 0.1 } }

[[modbus.devices.abb-B2x.measurement]]
name = "currentL1_A"
address = 0x5B0C
kind = { u32 = { multiplier = 0.01 } }

[[modbus.devices.abb-B2x.measurement]]
name = "currentL2_A"
address = 0x5B0E
kind = { u32 = { multiplier = 0.01 } }

[[modbus.devices.abb-B2x.measurement]]
name = "currentL3_A"
address = 0x5B10
kind = { u32 = { multiplier = 0.01 } }

[[modbus.devices.abb-B2x.measurement]]
name = "activePowerL1_W"
address = 0x5B16
kind = { s32 = { multiplier = 0.01 } }

[[modbus.devices.abb-B2x.measurement]]
name = "activePowerL2_W"
address = 0x5B18
kind = { s32 = { multiplier = 0.01 } }

[[modbus.devices.abb-B2x.measurement]]
name = "activePowerL3_W"
address = 0x5B1A
kind = { s32 = { multiplier = 0.01 } }

[[modbus.devices.abb-B2x.measurement]]
name = "reactivePowerL1_VAR"
address = 0x5B1E
kind = { s32 = { multiplier = 0.01 } }

[[modbus.devices.abb-B2x.measurement]]
name = "reactivePowerL2_VAR"
address = 0x5B20
kind = { s32 = { multiplier = 0.01 } }

[[modbus.devices.abb-B2x.measurement]]
name = "reactivePowerL3_VAR"
address = 0x5B22
kind = { s32 = { multiplier = 0.01 } }

# abb-B2x cumulative

[[modbus.devices.abb-B2x.measurement]]
name = "activePowerImportL1_Wh"
address = 0x5460
kind = { u64 = { multiplier = 10 } }

[[modbus.devices.abb-B2x.measurement]]
name = "activePowerImportL2_Wh"
address = 0x5464
kind = { u64 = { multiplier = 10 } }

[[modbus.devices.abb-B2x.measurement]]
name = "activePowerImportL3_Wh"
address = 0x5468
kind = { u64 = { multiplier = 10 } }

[[modbus.devices.abb-B2x.measurement]]
name = "activePowerExportL1_Wh"
address = 0x546C
kind = { u64 = { multiplier = 10 } }

[[modbus.devices.abb-B2x.measurement]]
name = "activePowerExportL2_Wh"
address = 0x5470
kind = { u64 = { multiplier = 10 } }

[[modbus.devices.abb-B2x.measurement]]
name = "activePowerExportL3_Wh"
address = 0x5474
kind = { u64 = { multiplier = 10 } }

[[modbus.devices.abb-B2x.measurement]]
name = "reactivePowerImportL1_VARh"
address = 0x5484
kind = { u64 = { multiplier = 10 } }

[[modbus.devices.abb-B2x.measurement]]
name = "reactivePowerImportL2_VARh"
address = 0x5488
kind = { u64 = { multiplier = 10 } }

[[modbus.devices.abb-B2x.measurement]]
name = "reactivePowerImportL3_VARh"
address = 0x548C
kind = { u64 = { multiplier = 10 } }

[[modbus.devices.abb-B2x.measurement]]
name = "reactivePowerExportL1_VARh"
address = 0x5490
kind = { u64 = { multiplier = 10 } }

[[modbus.devices.abb-B2x.measurement]]
name = "reactivePowerExportL2_VARh"
address = 0x5494
kind = { u64 = { multiplier = 10 } }

[[modbus.devices.abb-B2x.measurement]]
name = "reactivePowerExportL3_VARh"
address = 0x5498
kind = { u64 = { multiplier = 10 } }

[[modbus.devices.abb-B2x.measurement]]
name = "activeEnergyImportTotal_Wh"
address = 0x5000
kind = { u64 = { multiplier = 10 } }

[[modbus.devices.abb-B2x.measurement]]
name = "activeEnergyExportTotal_Wh"
address = 0x5004
kind = { u64 = { multiplier = 10 } }

[[modbus.devices.abb-B2x.measurement]]
name = "reactiveEnergyImportTotal_VARh"
address = 0x500C
kind = { u64 = { multiplier = 10 } }

[[modbus.devices.abb-B2x.measurement]]
name = "reactiveEnergyExportTotal_VARh"
address = 0x5010
kind = { u64 = { multiplier = 10 } }
